---
title: "R Notebook"
output: html_notebook
---

Selecting the right chart lab

# Learning objectives

- Understand which types of chart are best for categorical and continuous data
- Understand which types of chart are best for 1, 2, 3 and n variables

```{r}
library(tidyverse)
library(ggrepel)
```

```{r}
late_deliveries <- read_csv("data/late_deliveries.csv") %>% 
  janitor::clean_names()

recovery_times <- read_csv("data/recovery_times.csv") %>% 
  janitor::clean_names()

fitness_levels <- read_csv("data/fitness_levels.csv") %>% 
  janitor::clean_names()
```

```{r}
late_deliveries %>% 
  ggplot(aes(
    x = date,
    y = late_deliveries
  )) +
  geom_line() +
  labs(x = "Date",
       y = "Number of late deliveries") +
  ggtitle("Late deliveries by month")
```

```{r}
recovery_times <- recovery_times %>% 
  mutate(prognosis = factor(prognosis, levels = c(
    "Poor",
    "Average",
    "Good",
    "Excellent"
  )))

recovery_times %>% 
  ggplot(aes(x = treatment_group,
         y = recovery,
         fill = prognosis)) +
  geom_col() +
  facet_wrap(vars(prognosis), nrow = 1) +
  labs(x = "Treatment Group",
       y = "Recovery time",
       fill = "Prognosis") +
  ggtitle("Recovery times for treatment groups and control group", 
          subtitle = "Data includes patient prognosis")
```
geom_text(label = child)
```{r}
fitness_levels %>% 
  ggplot(aes(
    x = age,
    y = fitness_score
  )) +
  geom_line(aes(colour = child), show.legend = FALSE) +
  geom_text(data = fitness_levels %>% 
              group_by(child)  %>% 
              filter(age == 13), aes(label = child), check_overlap = TRUE) +
  facet_wrap(vars(group), nrow = 1)
```

3.2 connection

```{r}
blood_pressure <- read_csv("data/blood_pressure.csv")
car_use <- read_csv("data/car_use.csv")
```

```{r}
blood_pressure %>% 
  ggplot(aes(x = daily_saturated_fat_intake_mg,
             y = systolic_blood_pressure_mm_hg)) +
  geom_point()
```

```{r}
car_use <- car_use %>% 
  mutate(car_using_population = population * car_use_percent)
```


```{r}
car_use %>% 
  ggplot(aes(x = car_using_population,
             y = air_so2_concentration_ppm,
             label = city)) +
  geom_point() +
  geom_text_repel(size = 3, min.segment.length = 0.01, colour = "grey60") #+
  #scale_x_log10()
```

```{r}
d20_outcomes <- read_csv("data/d20_outcomes.csv")
d20x5_outcomes <- read_csv("data/d20x5_outcomes.csv")
```

```{r}
d20_outcomes %>% 
  ggplot(aes(x = outcome)) +
  geom_histogram()
```

```{r}
d20x5_outcomes %>% 
  ggplot(aes(x = outcome)) +
  geom_histogram()
```

```{r}
pension_surplus <- read_csv("data/pension_surplus.csv")
pension_liabilities <- read_csv("data/pension_liabilities.csv")
```

