---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(scales)
library(CodeClanData)
```

- Be able to customise the axis labels
- Be able to limit the plotted axes
- Be able to transform the scale of an axis
- Be able to flip a plot

```{r}
pets <- read_csv("data/pets.csv")

theme_set(theme_gray()) #set a default theme for the project
```

```{r}
pets %>% 
  ggplot(aes(age, weight, colour = sex)) +
  geom_point()
```

```{r}
pets %>% 
  ggplot(aes(age, weight, colour = sex)) +
  geom_point() +
  scale_x_continuous(breaks = 1:13) +
  scale_y_continuous(breaks = c(5, 7, 9, 11), labels = scales::percent)
```

```{r}
pets %>% 
  ggplot(aes(age, weight, colour = sex)) +
  geom_point() +
  scale_x_continuous(breaks = 1:13,
                     limits = c(1,8))
```

```{r}
pets %>% 
  ggplot(aes(age, weight, colour = sex)) +
  geom_line()

pets %>% 
  ggplot(aes(age, weight, colour = sex)) +
  geom_line() +
  scale_y_continuous(breaks = c(5, 7,9, 11),
                     limits = c(5, 9))

pets %>% 
  ggplot(aes(age, weight, colour = sex)) +
  geom_line() +
  scale_y_continuous(breaks = c(5, 7,9, 11),
                     limits = c(5, 9))

pets %>% 
  ggplot(aes(age, weight, colour = sex)) +
  geom_line() +
  coord_cartesian(ylim = c(5, 8))#useful to zoom in on plots b/c it doesn't turn any of the data into NAs, so assumes they still exist but are just outside the plot
```

```{r}
pets %>% 
  count(animal) %>% 
  ggplot(aes(x = animal, y = n)) +
  geom_col() +
  coord_flip()
```

```{r}
monthly_sales <- monthly_sales
```

```{r}
monthly_sales <- monthly_sales %>%
  mutate(month = factor(month, levels = c("Jan", "Feb", "March", "April"))) 

ggplot(monthly_sales) +
  aes(x = branch, y = sales, fill = month) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = ~dollar(., prefix = "£"))
  coord_flip()
```

```{r}
monthly_sales %>%
  mutate(sales_thousands = sales/1000) %>%
ggplot() +
  aes(x = branch, y = sales_thousands, fill = month) +
  geom_col(position = "dodge")  +
  coord_flip()+
  labs(y = "this",
       x = "that",
       title = "something else",
       caption = "a caption")
```

```{r}
monthly_sales %>%
ggplot() +
  aes(y = branch, x = sales, fill = month) +
  geom_col(position = "dodge")  +
  coord_flip()+
  labs(y = "this",
       x = "that",
       title = "something else",
       caption = "a caption") +
    scale_x_log10()
```

```{r}
scales::show_col(c("#343421", "#123456", "#ffbbcc", "#659fa5"))
pal <- scales::brewer_pal()

six_cols <- pal(6)

show_col(six_cols)

scales::
```

