---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```
```{r}
amount_spent <- c(9.1, 8.55, 14.32, 14.17, 14.34, 7.97, 9.79, 11.47, 12.44)
category <- c(
  "lunch",
  "dinner",
  "lunch",
  "lunch",
  "cinema",
  "drinks",
  "lunch",
  "lunch",
  "dinner"
)
my_week_of_spending <- tibble(
  amount_spent      = amount_spent,
  spending_category = category
)
summarise(my_week_of_spending, sum(amount_spent))
summarise(
  filter(
    my_week_of_spending, spending_category == "lunch"
  ),
  sum(amount_spent)
)
```

AmountSpent -> c(9.1, 8.55, 14.32, 14.17, 14.34, 7.97, 9.79, 11.47, 12.44)
Category <- c(
"Lunch",
"Dinner",
"Lunch",
"Lunch",
"Cinema",
"Drinks",
"Lunch",
"Lunch",
"Dinner")
my_week_of_spending <- tibble(
AmountSpent = AmountSpent, SpendingCategory = Category)
str(my.week.of.spending)
View(my.week.of.spending)
my.week.of.spending
summarise(my.week.of.spending,sum(AmountSpent))
summarise(filter(my.week.of.spending,SpendingCategory=='Lunch'),sum(AmountSpent))