---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(infer)
library(fastGraph)

telco <- read_csv("telecomms_churn.csv") %>% clean_names()
```



These 7043 represent the entire population (for purposes of this lesson)

We can calculate the population parameters
We can't usually do this b/c we don't usually have the whold population

```{r}
summary_popn <- telco %>% 
  summarise(
    mean_monthly_charges = mean(monthly_charges),
    mean_tenure = mean(tenure),
    prop_churn = sum(churn == "Yes")/n()
  )
```

```{r}
telco %>% 
  ggplot(aes(x = monthly_charges)) +
  geom_histogram(col = "white",
                 fill = "steel blue",
                 alpha = 0.7)
```

```{r}
telco %>% 
  ggplot(aes(x = tenure)) +
  geom_histogram(col = "white",
                 fill = "steel blue",
                 alpha = 0.7)
```

```{r}
telco %>% 
  ggplot(aes(x = churn)) +
  geom_bar(col = "white",
                 fill = "steel blue",
                 alpha = 0.7)
```

Let's start taking random samples for purposes of the lesson

```{r}
sample_200 <- telco %>% 
  rep_sample_n(200, reps = 1)
```

```{r}
summary_sample_200 <- sample_200 %>% 
  ungroup() %>% 
  summarise(
    mean_monthly_charges = mean(monthly_charges),
    mean_tenure = mean(tenure),
    prop_churn = sum(churn == "Yes")/n()
  )
```

```{r}
summary_sample_200 - summary_popn
```

```{r}
rep_sample_200 <- telco %>% 
  rep_sample_n(200, reps = 5000) %>% 
  summarise(
    mean_monthly_charges = mean(monthly_charges),
    mean_tenure = mean(tenure),
    prop_churn = sum(churn == "Yes")/n()
  )

rep_sample_200
```

```{r}
tenure_plot <- rep_sample_200 %>% 
  ggplot(aes(x = mean_tenure)) +
  geom_histogram(col = "white",
                 fill = "steel blue",
                 alpha = 0.7) +
  labs(x = "mean tenure from each sample")
tenure_plot

monthly_charges_plot <- rep_sample_200 %>% 
  ggplot(aes(x = mean_monthly_charges)) +
  geom_histogram(col = "white",
                 fill = "steel blue",
                 alpha = 0.7) +
  labs(x = "mean monthly charges from each sample")
monthly_charges_plot

prop_churn_plot <- rep_sample_200 %>% 
  ggplot(aes(x = prop_churn)) +
  geom_histogram(col = "white",
                 fill = "steel blue",
                 alpha = 0.7,
                 binwidth = 0.01) +
  labs(x = "Proportion churn from each sample")
prop_churn_plot
```

```{r}
std_errors <- rep_sample_200 %>% 
  summarise(
    se_mean_monthly_charges = sd(mean_monthly_charges),
    se_mean_tenure = sd(mean_tenure),
    se_prop_churn = sd(prop_churn)
  )

std_errors
```

```{r}
rep_sample_100 <- telco %>% 
  rep_sample_n(100, reps = 5000) %>% 
  summarise(
    mean_monthly_charges = mean(monthly_charges),
    mean_tenure = mean(tenure),
    prop_churn = sum(churn == "Yes")/n()
  )

rep_sample_100

std_errors_100 <- rep_sample_100 %>% 
  summarise(
    se_mean_monthly_charges = sd(mean_monthly_charges),
    se_mean_tenure = sd(mean_tenure),
    se_prop_churn = sd(prop_churn)
  )

std_errors_100
```

```{r}
shadeDist(
  xshade = c(60, 70),
  lower.tail = FALSE,
  ddist = "dnorm",
  parm1 = mean(rep_sample_200$mean_monthly_charges),
  parm2 = std_errors$se_mean_monthly_charges,
  xlab = "mean_monthly_charges"
)
```


# Confidence Intervals

```{r}
telco <- read_csv("CI_data/telecomms_churn.csv") %>% clean_names()

sample_200 <- telco %>% 
  rep_sample_n(size = 200, reps = 1)

summary_sample_200 <- sample_200 %>% 
  summarise(mean_monthly_charges = mean(monthly_charges),
            mean_tenure = mean(tenure),
            prop_churn = mean(churn == "Yes"))

summary_sample_200
```

```{r}
summary_pop <- telco %>% 
  summarise(mean_monthly_charges = mean(monthly_charges),
            mean_tenure = mean(tenure),
            prop_churn = mean(churn == "Yes"))

summary_pop
```

```{r}
sample_200 <- read_csv("CI_data/telecomms_churn_200_sample.csv") %>% 
  clean_names()
```

```{r}
bootstrap_resample_200 <- sample_200 %>% 
  rep_sample_n(size = 200,
               reps = 5000,
               replace = TRUE) %>% 
  summarise(mean_tenure = mean(tenure))
```

```{r}
bootstrap_resample_200 %>% 
  ggplot(aes(x = mean_tenure)) +
  geom_histogram(col = "white")
```

```{r}
bootstrap_resample_200 %>% 
  summarise(se_mean_tenure = sd(mean_tenure))
```

Confidence Intervals

```{r}
ci_95 <- bootstrap_resample_200 %>% 
  summarise(mean = mean(mean_tenure),
            lower_bound = quantile(mean_tenure, probs = 0.025),
            upper_bound = quantile(mean_tenure, probs = 0.975))

ci_95
```

Infer Workflow

```{r}
infer_resample <- sample_200 %>% 
  specify(response = tenure) %>% 
  generate(reps = 5000, type = "bootstrap") %>% 
  calculate(stat = "mean")
```

```{r}
inter_ci_95 <- infer_resample %>% 
  get_ci(level = 0.95, type = "percentile")


```

```{r}
infer_resample %>% 
  visualise(bins = 30) +
  shade_ci(endpoints = inter_ci_95)
```

```{r}
mean_infer <- infer_resample %>% 
  summarise(mean = mean(stat))
mean_infer
```

